### ISSUE TITLE
Excellent work!

### ISSUE THREAD

**Issue by jpriebe** [mcountis/dfp-events#6]
Your code is great -- very clever solution; thank you for sharing it.  We're using it to manage the visibility of responsive ad units.  At different breakpoints we load different ad sizes, and we hide/show them as appropriate.  To keep the number of impressions down (and keep the payload down for the user), we defer the loading of the various ad sizes until they're needed, but GPT forces the visibility of the ad after the async load is complete, which interferes with our visibility management code.  Tapping into the rendered event is a perfect way to maintain control over which ad is showing at a given breakpoint!

Events should be built into GPT -- have you spoken with anybody at Google about that?  My biggest concern is how fragile this all will be if Google changes their logging tomorrow or next week.

**Comment by gabrys** [comment]
Hey, we did, they said (don't quote me on this) "nice idea, but sorry, no"
