### ISSUE TITLE
Logging doesn't seem to work in <= IE8

### ISSUE THREAD

**Issue by bradleydeutsch** [mcountis/dfp-events#8]
Hey guys,

It seems calling the extended googletag.debug_log.log() method gets called once and then never again in browsers <= IE8

Any ideas, anyone else seen this?

**Comment by mcountis** [comment]
I haven't seen this.  Although at the moment I can only check old IEs via changing the Browser Mode from IE9. What are your circumstances? Code sample?

**Comment by bradleydeutsch** [comment]
Whoops, actually seems to be our issue... :S

Sorry!
