### ISSUE TITLE
Incorrect logical operator in debug_log.log line 113

### ISSUE THREAD

**Issue by harpere** [mcountis/dfp-events#9]
Shouldn't line 113:

if (!message && typeof (message.getMessageId()) !== 'number') return;

use || instead of &&   ?

if (!message || typeof (message.getMessageId()) !== 'number') return;

**Comment by mcountis** [comment]
Good catch.  I've changed the logic inside the method to always allow the method to passthrough to the older method as well.

https://github.com/mcountis/dfp-events/commit/f6af5ad6943cd33b9c985a37a3e92f1e94c110fb
